const PRODUCTS = [
  {
    id: 1,
    name: 'Платье миди в цветочный принт',
    category: 'Женская',
    price: 49,
    oldPrice: null,
    badge: 'new',
    colors: ['#e8c4a0', '#c9b8d4', '#a0c4e8'],
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: true,
    isSale: false,
    rating: 4.8,
    reviews: 24,
  },
  {
    id: 2,
    name: 'Блейзер оверсайз',
    category: 'Женская',
    price: 65,
    oldPrice: 89,
    badge: 'sale',
    colors: ['#2a2a2a', '#c4b090', '#8a9090'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: false,
    isSale: true,
    rating: 4.6,
    reviews: 38,
  },
  {
    id: 3,
    name: 'Джинсы прямого кроя',
    category: 'Мужская',
    price: 53,
    oldPrice: null,
    badge: 'new',
    colors: ['#3a5070', '#1a1a1a', '#c4a060'],
    sizes: ['28', '30', '32', '34', '36'],
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 52,
  },
  {
    id: 4,
    name: 'Льняная рубашка',
    category: 'Мужская',
    price: 349,
    oldPrice: 499,
    badge: 'sale',
    colors: ['#f0e8d0', '#c0d8c0', '#e0c8b8'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isNew: false,
    isSale: true,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: 5,
    name: 'Трикотажное платье',
    category: 'Женская',
    price: 399,
    oldPrice: 550,
    badge: 'sale',
    colors: ['#b04060', '#4a2a60', '#203050'],
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: false,
    isSale: true,
    rating: 4.9,
    reviews: 41,
  },
  {
    id: 6,
    name: 'Худи с вышивкой',
    category: 'Унисекс',
    price: 429,
    oldPrice: null,
    badge: 'new',
    colors: ['#f0f0f0', '#1a1a1a', '#4a7860'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    isNew: true,
    isSale: false,
    rating: 4.7,
    reviews: 29,
  },
  {
    id: 7,
    name: 'Юбка плиссе',
    category: 'Женская',
    price: 329,
    oldPrice: 480,
    badge: 'sale',
    colors: ['#d4a0b0', '#a0b4d4', '#d4c890'],
    sizes: ['XS', 'S', 'M', 'L'],
    isNew: false,
    isSale: true,
    rating: 4.4,
    reviews: 33,
  },
  {
    id: 8,
    name: 'Polo рубашка классическая',
    category: 'Мужская',
    price: 299,
    oldPrice: null,
    badge: 'new',
    colors: ['#1a3a60', '#c04030', '#204030'],
    sizes: ['S', 'M', 'L', 'XL'],
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviews: 18,
  },
];

function generateGradient(colors) {
  if (!colors || colors.length === 0) return '#e5e5e5';
  if (colors.length === 1) return colors[0];
  return `linear-gradient(135deg, ${colors[0]} 0%, ${colors[colors.length - 1]} 100%)`;
}

function formatPrice(price) {
  return '$' + price.toLocaleString('en-US');
}